export default {
  GET_ROWS: 'GET_ROWS',
  ROWS_RECEIVED: 'ROWS_RECEIVED',
  GET_SINGLE_ROW: 'GET_SINGLE_ROW',
  SINGLE_ROW_RECEIVED: 'SINGLE_ROW_RECEIVED',
  DELETE_ROW: 'DELETE_ROWS',
  ROW_DELETED: 'ROW_DELETED',
  ADD_EDIT_ROW: 'ADD_EDIT_ROW',
  ROW_ADDED_EDITED: 'ROW_ADDED_EDITED',
  SET_EDIT_DATA: 'SET_EDIT_DATA',
  CLEAR_ADD_EDIT_ROW: 'CLEAR_ADD_EDIT_ROW',
}
