export default {
  GET_ROWS: 'GET_ROWS',
  ROWS_RECEIVED: 'ROWS_RECEIVED',
  GET_SINGLE_ROW: 'GET_SINGLE_ROW',
  SINGLE_ROW_RECEIVED: 'SINGLE_ROW_RECEIVED',
  CREATE_ROW: 'CREATE_ROW',
  ROW_CREATED: 'ROW_CREATED',
  UPDATE_ROW: 'UPDATE_ROW',
  ROW_UPDATED: 'ROW_UPDATED',
  DELETE_ROW: 'DELETE_ROWS',
  ROW_DELETED: 'ROW_DELETED',
}
